autores/urls.py
from django.urls import path
from . import views

app_name = 'autores'

urlpatterns = [
    path('registro/', views.registrar, name='registrar'),
    path('registro/cadastro/', views.cadastro, name='cadastro'),
]

cursoDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('receitas.urls')),
    path('autores/', include('autores.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

receitas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.inicio, name="inicio"),
    path('receita/busca/', views.busca, name="busca"),
    path('receita/categoria/<int:categoria_id>/', views.receitaCategoria, name="receitas_por_categorias"),
    path('receita/<int:id>/', views.receitaDetalhe, name="receita_detalhe"),
]

autores/models.py
from django.db import models

# Create your models here.

receitas/models.py
from django.db import models
from django.contrib.auth.models import User

class ReceitaQuerySet(models.QuerySet):
    def publicado(self):
        return self.filter(esta_publicado=True)
    
class ReceitaManager(models.Manager):
    def get_queryset(self):
        return ReceitaQuerySet(self.model, using=self._db).filter(esta_publicado=True)

class Categoria(models.Model):
    nome = models.CharField(max_length=120)

    def __str__(self):
        return self.nome

class Receita(models.Model):
    titulo = models.CharField(max_length=120)
    descricao = models.CharField(max_length=165)
    tempo_preparo = models.IntegerField()
    unidade_tempo = models.CharField(max_length=30, default='Minutos')
    unidade_preparo = models.CharField(max_length=50)
    unidades_porcao = models.IntegerField()
    etapas_preparo = models.TextField()
    etapas_preparo_is_html = models.BooleanField(default=False)
    esta_publicado = models.BooleanField(default=True)
    capa = models.ImageField(upload_to='receitas/capas/%Y/%m/%d/', blank=True, default='')
    slug = models.SlugField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True, blank=True, default=None)
    autor = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, default=None)

    def __str__(self):
        return self.titulo
    
    objects = ReceitaManager()

autores/forms.py
import re
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

def add_attr(field, attr, value):
    attr_existente = field.widget.attrs.get(attr, '')
    field.widget.attrs[attr] = f'{attr_existente} {value}'.strip()

def add_placeholder(field, value):
    add_attr(field, 'placeholder', value)
    
def validar_senha_forte(password):
    regex = re.compile(r'^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).{8,}$')
    
    if not regex.match(password):
        raise ValidationError((
            'A senha deverá possuir 1 caractere maiúsculo, 1 caractere '
            'minúsculo, 1 símbolo especial (Ex: @, !, &) e ao menos 8 caracteres'
        ), code='Invalid')

class CadastroForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['first_name'], 'Ex: João')
        add_placeholder(self.fields['last_name'], 'Ex: Silva')
        add_placeholder(self.fields['username'], 'Digite seu usuário')
        add_placeholder(self.fields['email'], 'Ex: email@email.com')
        
    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Digite sua senha'
        }),
        error_messages={
            'required':'A senha deve possuir pelo menos 8 caracteres'
        },
        help_text=(
            'A senha deverá possuir 1 caractere maiúsculo, 1 caractere '
            'minúsculo, 1 símbolo especial (Ex: @, !, &) e ao menos 8 caracteres'
        ),
        validators=[validar_senha_forte]
    )
    confirm_password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Confirme sua senha'
        }),
        # error_messages='A confirmação de senha é obrigatória e deverá'
        # 'ter o mesmo valor do campo "senha"',
        # help_text='Repita sua senha inserida previamente'
    )
    class Meta:
        model= User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password'
        ]
        
        help_texts = {
            'email': 'O campo de e-mail precisa ser válido'
        }
        
        error_messages = {
            'username': {
                'required': 'O preenchimento do campo é obrigatório'
            }
        }
        
        widgets = {
            # 'first_name':forms.TextInput(attrs={
            #     'placeholder': 'Digite o primeiro nome'
            # }),
            'password':forms.PasswordInput(attrs={
                'placeholder': 'Digite sua senha'
            })
        }
        
    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        
        if 'vinicius' in first_name:
            raise ValidationError(
                'O nome não pode ser %(value)s',
                code='invalid',
                params={'value': 'vinicius'}
            )
        return first_name
        
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        
        if password != confirm_password:
            raise ValidationError({
                'password':'As senhas não conferem'
            })

autores/views.py
from django.shortcuts import redirect, render
from django.http import Http404,HttpResponse, HttpResponseNotAllowed
from .forms import CadastroForm

def registrar(request):
    dados_formulario = request.session.get('dados_formulario_cadastro', None)
    form = CadastroForm(dados_formulario)
    return render(request, 'autores/paginas/cadastro.html',
                {'form':form})

def cadastro(request):
    if not request.POST:
        raise Http404()
    POST = request.POST
    request.session['dados_formulario_cadastro'] = POST
    
    form = CadastroForm(POST)
    
    return redirect('autores:registrar')

receitas/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from receitas.models import Receita
from django.http import Http404
from django.db.models import Q
from utils.paginacao import cria_paginacao
import os
from django.contrib import messages

PER_PAGE = os.environ.get('PER_PAGE', 3)

def inicio(request):
    receitas = Receita.objects.all().order_by('-id')

    page_obj, intervalo_paginacao = cria_paginacao(request,receitas, PER_PAGE)
    return render(request, 'paginas/inicio.html', context={
        'receitas': page_obj,
        'pagina_detalhe': False,
        'intervalo_paginacao': intervalo_paginacao
    })

def receitaDetalhe(request, id):
    receita = get_object_or_404(
        Receita, id=id
    )

    return render(request, 'paginas/receita-detalhe.html', context={
        'receita': receita,
        'pagina_detalhe': True
    })

def receitaCategoria(request, categoria_id):
    receitas = get_list_or_404(
        Receita.objects.filter(categoria__id=categoria_id).order_by('-id')
    )
    
    page_obj, intervalo_paginacao = cria_paginacao(request,receitas, PER_PAGE)
    
    return render(request, 'paginas/receita-categoria.html', context={
        'receitas': page_obj,
        'categoria': receitas[0].categoria.nome,
        'pagina_detalhe': False,
        'intervalo_paginacao': intervalo_paginacao
    })
    
def busca(request):
    valor_busca = request.GET.get('q', '').strip()
    if not valor_busca:
        raise Http404()
    
    receitas = Receita.objects.filter(
        Q(titulo__icontains=valor_busca) | Q(descricao__icontains=valor_busca)
    )
    page_obj, intervalo_paginacao = cria_paginacao(request,receitas, PER_PAGE)
    
    return render(request, 'paginas/busca.html', context={
        'pagina_detalhe': False,
        'titulo_pagina': f'Busca por "{valor_busca}" | ',
        'valor_busca': valor_busca,
        'receitas':page_obj,
        'intervalo_paginacao':intervalo_paginacao,
        'consulta_adicional_url': f'&q={valor_busca}'
    })

autores/templates/autores/paginas/cadastro.html
{% extends 'global/base.html' %}

{% block title %}Cadastro{% endblock title %}

{% block content %}
    {% include 'paginas/layouts/mensagem.html' %}

    <div class="main-content center container">
        <h1>Cadastro</h1>
    </div>
    <div class="main-content container">
        <form action="{% url 'autores:cadastro' %}" method="post">
            <div class="form-content form-content-grid">
                {% csrf_token %}
                
                {% for field in form %}
                    <div class="form-group">    
                        <label for="{{field.id_for_label}}">{{field.label}}</label>
                        {{field}}
                        {% if field.help_text %}
                            <p class="help_text">{{field.help_text}}</p>
                        {% endif %}
                        {% for error in field.errors %}
                            <p class="error" style="color: red;">{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endfor %}

            </div>
            <div class="form-content form-content-grid">
                <div class="form-group">
                    <button type="submit">Enviar</button>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

receitas/templates/layouts/receita.html
<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        <a href="{% url 'receita_detalhe' receita.id %}">
            {% if receita.capa %}
                <img src="{{receita.capa.url}}" alt="{{receita.title}}">
            {% else %}
                <img src="" alt="Receita">
            {% endif %}
        </a>
    </div>
    <div class="recipe-title-container">
        <h2 class="recipe-title">{{ receita.titulo }}</h2>
    </div>
    <div class="recipe-author">
        <span class="recipe-author-item">
            {% if receita.autor is not None %}    
                <i class="fas fa-user"></i>
                {% if receita.autor.first_name %}
                    {{ receita.autor.first_name }} {{ receita.autor.last_name }}
                {% else %}
                    {{ receita.autor.username}}
                {% endif %}
            {% else %}
                <i class="fas fa-user"></i>
                Desconhecido
            {% endif %}
        </span>
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ receita.created_at|date:"d/m/Y" }} às {{ receita.created_at|date:"H:i" }}
        </span>
        {% if receita.categoria is not None %}
            <span class="recipe-author-item">
                <a href="{% url 'receitas_por_categorias' receita.categoria.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{ receita.categoria.nome }}</span>
                </a>
            </span>
        {% endif %}
    </div>
    <div class="recipe-content">
        <p>{{ receita.descricao }}</p>
    </div>
    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{receita.tempo_preparo}} {{ receita.unidade_tempo }}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> {{receita.unidade_preparo}}</h3>
            <div class="recipe-meta-text">
                {{receita.unidades_porcao}}
            </div>
        </div>
    </div>
    {% if pagina_detalhe is not True %}
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width" href="{% url 'receita_detalhe' receita.id %}">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
    {% endif %}

    {% if pagina_detalhe is True %}
        <div class="preparion-steps">
            {% if receita.etapas_preparo_is_html is True %}
                {{ receita.etapas_preparo|safe }}
            {% else %}
                {{ receita.etapas_preparo|linebreaksbr }}
            {% endif %}
        </div>
    {% endif %}
</div>

receitas/templates/layouts/search.html
<div class="search-container">
    <div class="container">
        <form action="{% url 'busca' %}" class="search-form">
            <input type="search" class="search-input" name="q" value="{{ valor_busca }}" required>
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>

receitas/templates/paginas/busca.html
{% extends 'global/base.html' %}

{% block title %}{{ titulo_pagina }}{% endblock title %}

{% block content %}
    <div class="main-content main-content-list container">
        {% for receita in receitas %}
            {% include 'layouts/receita.html' %}
        {% empty %}
            <div class="center">
                <h1>Não foram encontradas receitas</h1>
            </div>
        {% endfor %}
        {% include 'paginas/layouts/paginacao.html' %}
    </div>
{% endblock content %}

receitas/templates/paginas/home.html
{% extends 'global/base.html' %}

{% block title %}Página inicial{% endblock title %}

{% block content %}
    <div class="main-content main-content-list container">
        {% for receita in receitas %}
            {% include 'layouts/receita.html' %}
        {% endfor %}
    </div>
{% endblock content %}

receitas/templates/paginas/inicio.html
{% extends 'global/base.html' %}

{% block title %}Página inicial{% endblock title %}

{% block content %}
    {% include 'paginas/layouts/mensagem.html' %}
    <div class="main-content main-content-list container">
        {% for receita in receitas %}
            {% include 'layouts/receita.html' %}
        {% empty %}
            <div class="center">
                <h1>Não foram encontradas receitas</h1>
            </div>
        {% endfor %}
        {% include 'paginas/layouts/paginacao.html' %}
    </div>
{% endblock content %}

receitas/templates/paginas/layouts/mensagem.html
{% if messages %}
<div class="main-content center container messages-container">
    {% for message in messages %}
        <div class="message {{message.tags}}">
            {{message}}
        </div>
    {% endfor %}
</div>
{% endif %}

receitas/templates/paginas/layouts/paginacao.html
{% if receitas.has_other_pages %}
    <div class="container pagination">
        <div class="pagination-content">
            {% if intervalo_paginacao.primeira_pagina_fora_do_intervalo %}
                <a class="page-link page-item" href="?page=1{{consulta_adicional_url}}">1</a>
                <span class="page-item">...</span>
            {% endif %}

            {% for page in intervalo_paginacao.paginacao %}
                {% if pagination_range.current_page == page %}
                    <a class="page-link page-item page-current" href="?page={{ page }}{{consulta_adicional_url}}">{{ page }}</a>
                {% else %}
                    <a class="page-link page-item" href="?page={{ page }}{{consulta_adicional_url}}">{{ page }}</a>
                {% endif %}
            {% endfor %}
            
            {% if intervalo_paginacao.ultima_pagina_fora_do_intervalo %}
            <span class="page-item">...</span>
                <a class="page-link page-item" href="?page={{intervalo_paginacao.total_paginas}}{{consulta_adicional_url}}">{{intervalo_paginacao.total_paginas}}</a>
            {% endif %}
        </div>
    </div>
{% endif %}

receitas/templates/paginas/receita-categoria.html
{% extends 'global/base.html' %}

{% block title %}{{categoria}}{% endblock title %}

{% block content %}
    <div class="main-content main-content-list container">
        {% for receita in receitas %}
            {% include 'layouts/receita.html' %}
        {% endfor %}
    </div>
{% endblock content %}

receitas/templates/paginas/receita-detalhe.html
{% extends 'global/base.html' %}

{% block title %}{{receita.titulo}} {% endblock title %}

{% block content %}
        <div class="main-content main-content-detail container">
            {% include 'layouts/receita.html' %}
        </div>
{% endblock content %}